spring:
  profiles:
    active: dev
---
spring:
  profiles: dev

  application:
    name: gateway

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.226.1:8848

    gateway:
      routes:
        - id: student
          uri: lb://student
          predicates:
            - Path=/api/student/**
          filters:
            - RewritePath=/api(?<segment>/?.*), /$\{segment}
        - id: teacher
          uri: lb://teacher
          predicates:
            - Path=/api/teacher/**
          filters:
            - RewritePath=/api(?<segment>/?.*), /$\{segment}

server:
  port: 88

---
spring:
  profiles: pro